name: Deploy Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      OPENMODELS_ACCESS_TOKEN: ${{ secrets.OPENMODELS_ACCESS_TOKEN }}
      PROJECT_ID: zdtdtxajzydjqzuktnqx

    steps:
      - uses: actions/checkout@v3

      - uses: openmodels/setup-cli@v1
        with:
          version: latest

      - run: openmodels functions deploy github-action-deploy --project-ref $PROJECT_ID
